// <auto-generated />
using System;
using Libreria_VR_Peliculas.Implementaciones;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria_VR_Peliculas.Migrations
{
    [DbContext(typeof(Conexion))]
    [Migration("20260529183812_cambios")]
    partial class cambios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Actores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadP")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Artistico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premios")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Auditorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Usuarios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuarios");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Membresias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Membresias");

                    b.HasIndex("Status");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Descuentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Devoluciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Clientes")
                        .HasColumnType("int");

                    b.Property<int?>("Facturas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Multa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Multa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Clientes");

                    b.HasIndex("Facturas");

                    b.HasIndex("Peliculas");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Directores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadP")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premios")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directores");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Sucursales")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Sucursales");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Facturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Clientes")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Descuentos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rentas")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Ventas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Clientes");

                    b.HasIndex("Descuentos");

                    b.HasIndex("Rentas");

                    b.HasIndex("Ventas");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Formatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Formato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Subtitulada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Formatos");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Formatos_Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Formatos")
                        .HasColumnType("int");

                    b.Property<int?>("Inventarios")
                        .HasColumnType("int");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Formato")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Formatos");

                    b.HasIndex("Inventarios");

                    b.HasIndex("Peliculas");

                    b.ToTable("Formatos_Peliculas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Inventarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Formatos")
                        .HasColumnType("int");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<int?>("Proveedores")
                        .HasColumnType("int");

                    b.Property<int?>("Sucursales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Formatos");

                    b.HasIndex("Peliculas");

                    b.HasIndex("Proveedores");

                    b.HasIndex("Sucursales");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Membresias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RentasPermitidas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clasi_edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Directores")
                        .HasColumnType("int");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Estreno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Directores");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Proveedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Reclamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Facturas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Facturas");

                    b.ToTable("Reclamos");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Rentas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Clientes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Limite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Renta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio_Dia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Clientes");

                    b.ToTable("Rentas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Rentas_Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<int?>("Formatos_Peliculas")
                        .HasColumnType("int");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Dia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rentas")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Formatos_Peliculas");

                    b.HasIndex("Peliculas");

                    b.HasIndex("Rentas");

                    b.ToTable("Rentas_Peliculas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Repartos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Actores")
                        .HasColumnType("int");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<string>("Personaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Actores");

                    b.HasIndex("Peliculas");

                    b.ToTable("Repartos");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Sucursales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.TiposGeneros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Peliculas");

                    b.ToTable("TiposGeneros");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Roles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Roles");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Ventas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Clientes")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Venta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Clientes");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Ventas_Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Formatos_Peliculas")
                        .HasColumnType("int");

                    b.Property<int?>("Peliculas")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_U")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Ventas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Formatos_Peliculas");

                    b.HasIndex("Peliculas");

                    b.HasIndex("Ventas");

                    b.ToTable("Ventas_Peliculas");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Auditorias", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Usuarios", "_Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarios");

                    b.Navigation("_Usuario");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Clientes", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Membresias", "_Membresia")
                        .WithMany()
                        .HasForeignKey("Membresias");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Status", "_Status")
                        .WithMany()
                        .HasForeignKey("Status");

                    b.Navigation("_Membresia");

                    b.Navigation("_Status");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Devoluciones", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("Clientes");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Facturas", "_Factura")
                        .WithMany()
                        .HasForeignKey("Facturas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.Navigation("_Cliente");

                    b.Navigation("_Factura");

                    b.Navigation("_Pelicula");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Empleados", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Status", "_Status")
                        .WithMany()
                        .HasForeignKey("Status");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Sucursales", "_Sucursal")
                        .WithMany()
                        .HasForeignKey("Sucursales");

                    b.Navigation("_Status");

                    b.Navigation("_Sucursal");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Facturas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("Clientes");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Descuentos", "_Descuento")
                        .WithMany()
                        .HasForeignKey("Descuentos");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Rentas", "_Renta")
                        .WithMany()
                        .HasForeignKey("Rentas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Ventas", "_Venta")
                        .WithMany()
                        .HasForeignKey("Ventas");

                    b.Navigation("_Cliente");

                    b.Navigation("_Descuento");

                    b.Navigation("_Renta");

                    b.Navigation("_Venta");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Formatos_Peliculas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Formatos", "_Formato")
                        .WithMany()
                        .HasForeignKey("Formatos");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Inventarios", "_Inventario")
                        .WithMany()
                        .HasForeignKey("Inventarios");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.Navigation("_Formato");

                    b.Navigation("_Inventario");

                    b.Navigation("_Pelicula");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Inventarios", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Formatos", "_Formato")
                        .WithMany()
                        .HasForeignKey("Formatos");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Proveedores", "_Proveedor")
                        .WithMany()
                        .HasForeignKey("Proveedores");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Sucursales", "_Sucursal")
                        .WithMany()
                        .HasForeignKey("Sucursales");

                    b.Navigation("_Formato");

                    b.Navigation("_Pelicula");

                    b.Navigation("_Proveedor");

                    b.Navigation("_Sucursal");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Peliculas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Directores", "_Director")
                        .WithMany()
                        .HasForeignKey("Directores");

                    b.Navigation("_Director");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Reclamos", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Facturas", "_Factura")
                        .WithMany()
                        .HasForeignKey("Facturas");

                    b.Navigation("_Factura");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Rentas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("Clientes");

                    b.Navigation("_Cliente");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Rentas_Peliculas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Formatos_Peliculas", "_Formato_Pelicula")
                        .WithMany()
                        .HasForeignKey("Formatos_Peliculas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Rentas", "_Renta")
                        .WithMany()
                        .HasForeignKey("Rentas");

                    b.Navigation("_Formato_Pelicula");

                    b.Navigation("_Pelicula");

                    b.Navigation("_Renta");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Repartos", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Actores", "_Actor")
                        .WithMany()
                        .HasForeignKey("Actores");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.Navigation("_Actor");

                    b.Navigation("_Pelicula");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.TiposGeneros", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.Navigation("_Pelicula");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Usuarios", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Roles", "_Rol")
                        .WithMany()
                        .HasForeignKey("Roles");

                    b.Navigation("_Rol");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Ventas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("Clientes");

                    b.Navigation("_Cliente");
                });

            modelBuilder.Entity("Libreria_VR_Peliculas.Entidades.Ventas_Peliculas", b =>
                {
                    b.HasOne("Libreria_VR_Peliculas.Entidades.Formatos_Peliculas", "_Formato_Pelicula")
                        .WithMany()
                        .HasForeignKey("Formatos_Peliculas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Peliculas", "_Pelicula")
                        .WithMany()
                        .HasForeignKey("Peliculas");

                    b.HasOne("Libreria_VR_Peliculas.Entidades.Ventas", "_Venta")
                        .WithMany()
                        .HasForeignKey("Ventas");

                    b.Navigation("_Formato_Pelicula");

                    b.Navigation("_Pelicula");

                    b.Navigation("_Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
